<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ScreenTimeGuardian.ControlPanel</AssemblyName>
    <RootNamespace>ScreenTimeGuardian.ControlPanel</RootNamespace>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Fonts\*.ttf" />
    <Resource Include="icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Guardian.Contracts\Guardian.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>
</Project>
